language: java
jdk:
  - oraclejdk8
branches:
  only:
  - master
  - Documentation
  
script: mvn --settings travis-settings.xml clean test verify deploy site

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
