language: java
jdk:
  - oraclejdk8
branches:
  only:
  - master
  - debug
  
script: mvn --settings travis-settings.xml clean test verify deploy

notifications:
  webhooks: $DISCORD_WEBHOOK

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
