language: java
jdk:
  - oraclejdk8
  
branches:
  only:
  - master
  - Documentation
  
script: mvn --settings travis-settings.xml deploy site site-deploy

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
